import { signalStatus } from "@/components/signal/status";
import { SIGNAL_TEMPLATES } from "@/constants/signalTemplates";
import { signalTimestamp } from "@/lib/signalCalendar";
import type { Asset } from "@/types";

export interface SignalPackRow {
  order: number;
  phase: string;
  label: string;
  platform: string;
  assetType: string;
  /** ISO 8601, or "" when the mission has no launch date. */
  scheduledAt: string;
  status: "not_loaded" | "in_prep" | "flight_ready";
  /** Linked asset body; empty unless flight-ready content exists. */
  content: string;
}

export interface SignalPackFile {
  name: string;
  content: string;
}

export const SIGNAL_PACK_README = `# LaunchDeckAI — Signal Pack

This pack contains your full launch promotion sequence.

## Files
- \`signal-schedule.csv\` — every signal with platform, timing, and status. Import into Buffer or Later as a posting schedule.
- \`signal-schedule.json\` — the same schedule as structured data for Zapier, Make, or n8n.
- \`content/*.txt\` — ready-to-post copy for each flight-ready signal.

## Import tips
- **Buffer / Later:** create posts from each row in the CSV; paste the matching \`content/*.txt\` body.
- **Zapier / Make / n8n:** trigger on \`scheduledAt\`, read \`label\`/\`platform\`, and post the content file.

Generated by LaunchDeckAI.`;

export function buildSignalPackRows(assets: Asset[], launchDate?: number): SignalPackRow[] {
  return [...SIGNAL_TEMPLATES]
    .sort((a, b) => a.order - b.order)
    .map((s) => {
      const ts = signalTimestamp(s.relativeTiming, launchDate);
      const linked = assets.find((a) => a.signalId === s.id);
      const status = signalStatus(s.id, assets);
      return {
        order: s.order,
        phase: s.phase,
        label: s.label,
        platform: s.platform,
        assetType: s.assetType,
        scheduledAt: ts ? new Date(ts).toISOString() : "",
        status,
        content: status === "flight_ready" ? (linked?.content?.trim() ?? "") : "",
      };
    });
}

function csvCell(value: string): string {
  return /[",\n\r]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

export function buildSignalScheduleCsv(rows: SignalPackRow[]): string {
  const header = ["order", "phase", "label", "platform", "assetType", "scheduledAt", "status"];
  const body = rows.map((r) =>
    [r.order, r.phase, r.label, r.platform, r.assetType, r.scheduledAt, r.status]
      .map((c) => csvCell(String(c)))
      .join(","),
  );
  return [header.join(","), ...body].join("\n");
}

export function buildSignalScheduleJson(rows: SignalPackRow[]): string {
  const meta = rows.map(({ content, ...rest }) => rest);
  return JSON.stringify(meta, null, 2);
}

export function slugifyLabel(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function buildSignalPackFiles(assets: Asset[], launchDate?: number): SignalPackFile[] {
  const rows = buildSignalPackRows(assets, launchDate);
  const files: SignalPackFile[] = [
    { name: "signal-schedule.csv", content: buildSignalScheduleCsv(rows) },
    { name: "signal-schedule.json", content: buildSignalScheduleJson(rows) },
    { name: "README.md", content: SIGNAL_PACK_README },
  ];
  for (const r of rows) {
    if (r.status === "flight_ready" && r.content) {
      const num = String(r.order).padStart(2, "0");
      files.push({ name: `content/${num}-${slugifyLabel(r.label)}.txt`, content: r.content });
    }
  }
  return files;
}
